Frontend react2
Naveen-Jaisankar/COMP47360-Web-Application pull request #23
Opened 2024-07-12 10:10 UTC by Ritwik-Ritz

Contains implementation for map features like heatmap, search , map styles, alert cards and also has matas' code for user dashboard

2024-07-12 11:22 UTC, Naveen-Jaisankar requested changes

2024-07-12 11:22 UTC, Naveen-Jaisankar commented on FrontEnd/air-quality-app/src/components/usersidebar.jsx
> +                <p className="text-lg mt-2">Welcome back, User</p>
Can you move these static constants to constants.js file

2024-07-12 11:22 UTC, Naveen-Jaisankar commented on FrontEnd/air-quality-app/src/pages/ForgotPassword.jsx
> +        <Typography variant="h4" className="mb-4 font-bold">Reset Password</Typography>
Please move this constants to constants file

2024-07-12 11:22 UTC, Naveen-Jaisankar commented on FrontEnd/air-quality-app/src/axios.jsx
I guess we already have a base.js file in the api directory which has same code. Could you please delete it?

2024-07-12 11:22 UTC, Naveen-Jaisankar commented on FrontEnd/air-quality-app/src/pages/UserDashboard.jsx
> +    days.push({ day: label, PersonalExposure: Math.random() * 100, AQI: Math.random() * 100 });
Can you round off the value of personal exposure and aqi to two decimal point

2024-07-12 11:22 UTC, Naveen-Jaisankar commented on FrontEnd/air-quality-app/src/pages/UserDashboard.jsx
Please move all static constants to constants.js file

2024-07-12 11:22 UTC, Naveen-Jaisankar commented on FrontEnd/air-quality-app/src/pages/ForgotPassword.jsx
> +            <Button type="submit" variant="contained" color="primary" fullWidth className="mt-4"> {constant.loginConsts.login_btn} </Button>
I guess login button doesn't suit well for this context...Can you change the text to submit or reset...
![image](https://github.com/user-attachments/assets/3fba7fdf-194f-4ab3-adf6-00f347583760)

2024-07-12 11:22 UTC, Naveen-Jaisankar commented on FrontEnd/air-quality-app/src/pages/Login.jsx
Can you add email validation here....,use regex validation.. 
also in register page as well...

2024-07-12 11:22 UTC, Naveen-Jaisankar commented on FrontEnd/air-quality-app/src/App.jsx
> +import UserDashboard from './pages/UserDashboard';
Both /user and /user/userdashboard display the same content. /user/userdashboard displays same content without the sidebar. Are we utilizing both endpoints?

2024-07-12 11:22 UTC, Naveen-Jaisankar commented on FrontEnd/air-quality-app/src/components/usersidebar.jsx
Place this side bar in all required places...
/user/history/
/user/dailyform/

2024-07-14 16:14 UTC, jmacap commented on FrontEnd/air-quality-app/src/App.jsx
> +import UserDashboard from './pages/UserDashboard';
This might have to be changed into import Dashboard from './pages/UserDashboard', rather than import UserDashboard as there no longer seems to be a UserDashboard export

2024-07-14 16:15 UTC, Ritwik-Ritz commented on FrontEnd/air-quality-app/src/App.jsx
> +import UserDashboard from './pages/UserDashboard';
btw we're no longer using this import

2024-07-15 13:23 UTC, merged